version: '3'

services:
  web-app:
    image: web-app-image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8001
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=WEB-App-DB
    ports:
      - "8001:8001"
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: WEB-App-DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: