// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/car": {
            "get": {
                "description": "Добавляет новый автомобиль",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "автомобиль"
                ],
                "summary": "Добавить новый автомобиль",
                "parameters": [
                    {
                        "description": "Данные авто",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Automobile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Ошибка на сервере"
                    }
                }
            }
        },
        "/car/:id": {
            "get": {
                "description": "Возвращает  автомобиль",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "автомобиль"
                ],
                "summary": "Получить автомобиль по id",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Ошибка на сервере"
                    }
                }
            },
            "delete": {
                "description": "Удаляет  автомобиль",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "автомобиль"
                ],
                "summary": "Удалить автомобиль",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Ошибка на сервере"
                    }
                }
            },
            "patch": {
                "description": "Обновляет  автомобиль",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "автомобиль"
                ],
                "summary": "Обновить автомобиль",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Ошибка на сервере"
                    }
                }
            }
        },
        "/cars": {
            "get": {
                "description": "Возвращает  список автомобилей",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "автомобиль"
                ],
                "summary": "Получить список автомобилей",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Ошибка на сервере"
                    }
                }
            }
        },
        "/inspection": {
            "post": {
                "description": "Добавляет тех осмотр",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "тех осмотр"
                ],
                "summary": "Добавить тех осмотр",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Ошибка на сервере"
                    }
                }
            }
        },
        "/inspection/:id": {
            "get": {
                "description": "Возвращает тех осмотр",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "тех осмотр"
                ],
                "summary": "Получить тех осмотр по id",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Ошибка на сервере"
                    }
                }
            },
            "delete": {
                "description": "Удаляет тех осмотр",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "тех осмотр"
                ],
                "summary": "Удалить тех осмотр по id",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Ошибка на сервере"
                    }
                }
            },
            "patch": {
                "description": "Обновляет  данные тех осмотра",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "тех осмотр"
                ],
                "summary": "Обновить данные о тех осмотре",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Ошибка на сервере"
                    }
                }
            }
        },
        "/inspections": {
            "get": {
                "description": "Возвращает список тех осмотров",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "тех осмотр"
                ],
                "summary": "Получить список тех осмотров",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Ошибка на сервере"
                    }
                }
            }
        },
        "/report": {
            "get": {
                "description": "Возвращает агрегированные данные по автомобилям",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "автомобиль"
                ],
                "summary": "Получить отчёт по автомобилям",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Ошибка на сервере"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Automobile": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "license_plate": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "registration_date": {
                    "type": "string"
                },
                "release_date": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Web-App API",
	Description:      "API для управления автопарком.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
